import { createStyles } from "@mantine/core";

export const UseProductDetailsPageStyle = createStyles((theme) => ({
  imageIcon: {
    alignSelf: 'stretch',
    flex: 1,
    position: 'relative',
    borderRadius: 12,
    maxWidth: '100%',
    overflow: 'hidden',
    maxHeight: '100%',
    objectFit: 'cover',
  },
  navigateBeforeIcon: {
    position: 'relative',
    width: 24,
    height: 24,
    overflow: 'hidden',
    flexShrink: 0,
  },
  frameChild: {
    flex: 1,
    position: 'relative',
    borderRadius: 12,
    maxWidth: '100%',
    overflow: 'hidden',
    height: 158,
    objectFit: 'cover',
  },
  frameItem: {
    flex: 1,
    position: 'relative',
    borderRadius: 12,
    maxWidth: '100%',
    overflow: 'hidden',
    height: 158,
    objectFit: 'cover',
  },
  rectangleParent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  productImages: {
    flex: 1,
    height: 553,
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 24,
  },
  hoyaLinearis: {
    alignSelf: 'stretch',
  },
  div: {
    position: 'relative',
  },
  div1: {
    fontSize: 24,
    textDecoration: 'line-through',
    fontWeight: 300,
    color: 'rgba(209, 31, 31, 0.5)',
  },
  hoyaLinearisParent: {
    width: 486,
    flexDirection: 'column',
    padding: '0 4px 0 0',
    boxSizing: 'border-box',
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  frameGroup: {
    alignSelf: 'stretch',
  },
  l: {
    alignSelf: 'stretch',
    position: 'relative',
    fontSize: 20,
    color: '#343434',
  },
  frameGroup: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    gap: 16,
  },
  quantityChild: {
    border: '2px solid #343434',
    fontFamily: 'Open Sans',
    fontSize: 20,
    backgroundColor: 'transparent',
    borderRadius: 4,
    display: 'flex',
    flexDirection: 'row',
    padding: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantity: {
    justifyContent: 'center',
    gap: 16,
  },
  frameSelect: {
    borderRadius: 4,
    border: '2px solid #343434',
    boxSizing: 'border-box',
    height: 38,
    padding: 4,
    justifyContent: 'center',
  },
  quantityParent: {
    justifyContent: 'flex-start',
    gap: 70,
    fontSize: 20,
  },
  addToCart: {
    position: 'relative',
    fontSize: 20,
    fontFamily: 'Open Sans',
    color: '#fff',
    textAlign: 'center',
  },
  addToCartButton: {
    cursor: 'pointer',
    backgroundColor: '#3b823e',
    border: 'none',
    borderRadius: 12,
    boxShadow: '0 8px 23px rgba(0, 0, 0, 0.13)',
    width: 344,
    height: 64,
    display: 'flex',
    flexDirection: 'row',
    boxSizing: 'border-box',
    alignItems: 'center',
    justifyContent: 'center',
  },
  frameParent: {
    alignSelf: 'stretch',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    gap: 24,
  },
  delivery: {
    margin: 0,
    fontWeight: 600,
  },
  enterYourPincode: {
    margin: 0,
    fontSize: 16,
    color: 'rgba(52, 52, 52, 0.6)',
  },
  check: {
    backgroundColor: 'transparent',
    fontSize: 20,
    fontFamily: 'Open Sans',
  },
  pincodeChild: {
    border: '2px solid #343434',
    borderRadius: 4,
    boxSizing: 'border-box',
    width: 146,
    height: 38,
    display: 'flex',
    flexDirection: 'row',
    padding: 8,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  check: {
    cursor: 'pointer',
    border: 0,
    padding: 0,
    position: 'relative',
    fontWeight: 600,
    color: '#3b823e',
    textAlign: 'left',
    display: 'inline-block',
  },
  deliveryEnterYourPincodeToParent: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 16,
  },
  deliveryEnterYourPincodeToParent: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 12,
  },
  deliveryAvailableFor: {
    margin: 0,
  },
  deliveryCheckResult: {
    alignSelf: 'stretch',
    borderRadius: 12,
    border: '1px solid #343434',
    display: 'flex',
    flexDirection: 'row',
    padding: 8,
    alignItems: 'center',
    justifyContent: 'flex-start',
    fontSize: 16,
    color: 'rgba(52, 52, 52, 0.6)',
  },
  deliveryInfo: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    gap: 20,
    fontSize: 20,
  },
  productDetails: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    gap: 40,
  },
  details: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 80,
    width: '90%',
    fontSize: 32,
    fontFamily: 'Open Sans',
    paddingBottom: 56,
    paddingTop: 56,
    justifyContent: 'space-evenly',
    margin: '0 auto',
  },
}));
